const sampleProducts = [
  {
    name: "Organic Red Apples",
    price: 4.99,
    originalPrice: 6.99,
    image: "/src/assets/fresh-apples.jpg",
    rating: 4.8,
    reviews: 124,
    category: "Fruits",
    inStock: true,
    discount: "30% OFF",
  },
  {
    name: "Fresh Bananas",
    price: 2.99,
    originalPrice: 3.99,
    image: "/src/assets/fresh-bananas.jpg",
    rating: 4.9,
    reviews: 89,
    category: "Fruits",
    inStock: true,
    discount: "25% OFF",
  },
  {
    name: "Organic Carrot",
    price: 3.49,
    originalPrice: 4.49,
    image: "/src/assets/fresh-carrots.jpg",
    rating: 4.7,
    reviews: 156,
    category: "Vegetables",
    inStock: true,
    discount: "25% OFF",
  },
  {
    name: "Fresh Dairy Pack",
    price: 12.99,
    originalPrice: 15.99,
    image: "/src/assets/dairy-products.jpg",
    rating: 4.6,
    reviews: 203,
    category: "Dairy",
    inStock: true,
    discount: "25% OFF",
  },
  {
    name: "Healthy Snack Mix",
    price: 8.99,
    originalPrice: 11.99,
    image: "/src/assets/healthy-snacks.jpg",
    rating: 4.8,
    reviews: 78,
    category: "Snack",
    inStock: false,
    discount: "25% OFF",
  },
  {
    name: "Premium Organic Apples",
    price: 7.99,
    image: "/src/assets/fresh-bananas.jpg",
    rating: 4.9,
    reviews: 95,
    category: "Fruits",
    inStock: true,
    discount: "25% OFF",
  },
];

module.exports = { data: sampleProducts };
